### ISSUE TITLE
Q/A: logo/ necessary in npm package?

### ISSUE THREAD

**Issue by magnudae** [arnemahl/pockito#16]
When fetching pockito I get the logo/ folder aswell. 
This folder contains 60% of the size of pockito. Is it possible to get pockito without the logos?

**Comment by arnemahl** [comment]
Yes, good idea. We can remove the logo folder by adding a line to [.nmpignore](../blob/master/.npmignore). Before I fix it, should I remove some more stuff? Or rather, what should come with the npm package?

**Comment by magnudae** [comment]
Great. 
Not sure, but is it common to have examples and test-cases in the published package?

**Comment by arnemahl** [comment]
I looked at React and it comes with `lib/` (source) in addition to the code required to run it and some info-files (LICENCE, PATENTS and README.md). So I guess I'll do the same (for the files that I have).

##### .npmignore

```
logo/
test/
usage-examples/
.npmignore
.travis.yml
API.md
CONTRIBUTING.md
TODO.md
```

##### Included stuff

```
src/
dist/
package.json
README.md
```

PS: Some files are npmignored automatically while some cannot be npmignored ([link](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package)).

What do you think?

**Comment by arnemahl** [comment]
Just merged the changes and published to npm. Let me know if you have any more good ideas!
